[package]
name = "DPNFramework"
version = "1.5.0"

[addresses]
std = "0x1"
DiemFramework = "0x1"
DiemRoot = "0xA550C18"
TreasuryCompliance = "0xB1E55ED"
CurrencyInfo = "0xA550C18"
VMReserved = "0x0"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/move-stdlib", rev = "main" }
MoveNursery = { local = "../../../../../move-stdlib/nursery" }
