[package]
name = "BasicCoin"
version = "0.0.0"

[addresses]
NamedAddr = "0xDEADBEEF"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/move-stdlib", ref = "main", addr_subst = { "std" = "0x1" } }
