[package]
name = "MoveAsyncLib"
version = "0.0.0"

[addresses]
std = "_"
Async = "_"

[dev-addresses]
std = "0x1"
Async = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/move-stdlib", rev = "main" }
