[package]
name = "EvmExamples"
version = "1.5.0"

[addresses]
std = "0x1"
Evm = "0x2"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/move-stdlib", rev = "main" }
MoveNursery = { local = "../../move-stdlib/nursery" }
EvmStdlib = { local = "../stdlib" }
