[package]
name = "BasicCoin"
version = "0.0.0"

[addresses]
BasicCoin = "0xBC"

[dependencies]
MoveStdlib = { git = "https://github.com/eigerco/move-stdlib", rev = "main", addr_subst = { "std" = "0x1" } }
