[package]
name = "ERC721Mock"
version = "0.0.0"

[addresses]
std = "0x1"
Evm = "0x2"

[dependencies]
EvmStdlib = { local = "../../../stdlib" }
MoveStdlib = { git = "https://github.com/eigerco/move-stdlib", rev = "main" }
